### ISSUE TITLE
Switch to `SvelteAdd`

### ISSUE THREAD

**Issue by sahinf** [sahinf/PTDatabaseApp#4]
Based on this [issue](https://github.com/sveltejs/svelte/issues/7079#issuecomment-1003179431) that I faced when trying to use `DaisyUI` tables, I may want to migrate the project to use svelteadd. 

It's not necessary to do this but it should make future integrations easier if needed. Currently `tailwind` and `postcss` integrations have proven to induce massive amounts of frustration and headaches 🥲

**Comment by babichjacob** [comment]
Let it be known that `svelte-add` works with Vite even without SvelteKit, so you can choose an easier upgrade path:

1. You can replace Rollup with Vite in your existing project, perhaps by following [the main idea of this video tutorial](https://www.youtube.com/watch?v=D66wC4VsgVU) (some things have changed over time, like the move from `@svitejs/vite-plugin-svelte` to `@sveltejs/vite-plugin-svelte`).

2. You can start a new Vite app through the official Vite app initializer `npm create vite`, or through [Svelte Add's Vite app initializer](https://github.com/svelte-add/svelte-add#%EF%B8%8F-creating-a-vite-powered-svelte-app-with-integrations) but ours has confusing bugs so it might not be worth trying yet, and then copy over your existing app files (mainly the ones in `src`) into your new project.

Or you might wish to try both before starting a whole migration. It helps a lot to know what a working setup looks like in 2. before trying 1. so that you are less likely to make mistakes or end up with invalid configuration.

You can ask for help in the [official Svelte Discord server](https://svelte.dev/chat) and especially @ping me if it involves Svelte Add.

**Comment by sahinf** [comment]
Wow, thank you for your help. I just made this issue as a reference for myself, I never meant to ping or bother you. Regardless, I was able to migrate to Vite through
1. The video you [linked](https://www.youtube.com/watch?v=D66wC4VsgVU)
2. Importing using destructuring `import {svelte} from '@sveltejs/vite-plugin-svelte'`
3. specifying `svelte-preprocess` in `vite.config.json` through [this link](https://github.com/drannex42/svelte-capacitor/issues/15)

Without (3), the Svelte compiler was having problems parsing `ts`.
